require 'spec_helper'

describe SemanticRange do
  it 'gtr' do
    # [version, range, loose]
    # Version should be greater than range
    expect(SemanticRange.gtr('1.3.0', '~1.2.2', false)).to eq(true)
    expect(SemanticRange.gtr('0.7.1-1', '~0.6.1-1', false)).to eq(true)
    expect(SemanticRange.gtr('2.0.1', '1.0.0 - 2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('1.0.1-beta1', '1.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.0.0', '1.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.1.1', '<=2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('1.3.0', '~1.2.2', false)).to eq(true)
    expect(SemanticRange.gtr('0.7.1-1', '~0.6.1-1', false)).to eq(true)
    expect(SemanticRange.gtr('2.0.1', '1.0.0 - 2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('1.0.1-beta1', '1.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.0.0', '1.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.1.1', '<=2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('3.2.9', '<=2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.0.0', '<2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('1.2.5', '0.1.20 || 1.2.4', false)).to eq(true)
    expect(SemanticRange.gtr('3.0.0', '2.x.x', false)).to eq(true)
    expect(SemanticRange.gtr('1.3.0', '1.2.x', false)).to eq(true)
    expect(SemanticRange.gtr('3.0.0', '1.2.x || 2.x', false)).to eq(true)
    expect(SemanticRange.gtr('5.0.1', '2.*.*', false)).to eq(true)
    expect(SemanticRange.gtr('1.3.3', '1.2.*', false)).to eq(true)
    expect(SemanticRange.gtr('4.0.0', '1.2.* || 2.*', false)).to eq(true)
    expect(SemanticRange.gtr('3.0.0', '2', false)).to eq(true)
    expect(SemanticRange.gtr('2.4.2', '2.3', false)).to eq(true)
    expect(SemanticRange.gtr('2.5.0', '~2.4', false)).to eq(true)
    expect(SemanticRange.gtr('2.5.5', '~2.4', false)).to eq(true)
    expect(SemanticRange.gtr('3.3.0', '~>3.2.1', false)).to eq(true)
    expect(SemanticRange.gtr('2.2.3', '~1', false)).to eq(true)
    expect(SemanticRange.gtr('2.2.4', '~>1', false)).to eq(true)
    expect(SemanticRange.gtr('3.2.3', '~> 1', false)).to eq(true)
    expect(SemanticRange.gtr('1.1.2', '~1.0', false)).to eq(true)
    expect(SemanticRange.gtr('1.1.0', '~ 1.0', false)).to eq(true)
    expect(SemanticRange.gtr('1.2.0', '<1.2', false)).to eq(true)
    expect(SemanticRange.gtr('1.2.1', '< 1.2', false)).to eq(true)
    expect(SemanticRange.gtr('2.0.0beta', '1', true)).to eq(true)
    expect(SemanticRange.gtr('0.6.0', '~v0.5.4-pre', false)).to eq(true)
    expect(SemanticRange.gtr('0.6.1-pre', '~v0.5.4-pre', false)).to eq(true)
    expect(SemanticRange.gtr('0.8.0', '=0.7.x', false)).to eq(true)
    expect(SemanticRange.gtr('0.8.0-asdf', '=0.7.x', false)).to eq(true)
    expect(SemanticRange.gtr('0.7.0', '<0.7.x', false)).to eq(true)
    expect(SemanticRange.gtr('1.3.0', '~1.2.2', false)).to eq(true)
    expect(SemanticRange.gtr('2.2.3', '1.0.0 - 2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('1.0.1', '1.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('3.0.0', '<=2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.9999.9999', '<=2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.2.9', '<=2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.9999.9999', '<2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('2.2.9', '<2.0.0', false)).to eq(true)
    expect(SemanticRange.gtr('3.1.3', '2.x.x', false)).to eq(true)
    expect(SemanticRange.gtr('1.3.3', '1.2.x', false)).to eq(true)
    expect(SemanticRange.gtr('3.1.3', '1.2.x || 2.x', false)).to eq(true)
    expect(SemanticRange.gtr('3.1.3', '2.*.*', false)).to eq(true)
    expect(SemanticRange.gtr('1.3.3', '1.2.*', false)).to eq(true)
    expect(SemanticRange.gtr('3.1.3', '1.2.* || 2.*', false)).to eq(true)
    expect(SemanticRange.gtr('3.1.2', '2', false)).to eq(true)
    expect(SemanticRange.gtr('2.4.1', '2.3', false)).to eq(true)
    expect(SemanticRange.gtr('2.5.0', '~2.4', false)).to eq(true)
    expect(SemanticRange.gtr('3.3.2', '~>3.2.1', false)).to eq(true)
    expect(SemanticRange.gtr('2.2.3', '~1', false)).to eq(true)
    expect(SemanticRange.gtr('2.2.3', '~>1', false)).to eq(true)
    expect(SemanticRange.gtr('1.1.0', '~1.0', false)).to eq(true)
    expect(SemanticRange.gtr('1.0.0', '<1', false)).to eq(true)
    expect(SemanticRange.gtr('2.0.0beta', '1', true)).to eq(true)
    expect(SemanticRange.gtr('1.0.0beta', '<1', true)).to eq(true)
    expect(SemanticRange.gtr('1.0.0beta', '< 1', true)).to eq(true)
    expect(SemanticRange.gtr('0.8.2', '=0.7.x', false)).to eq(true)
    expect(SemanticRange.gtr('0.7.2', '<0.7.x', false)).to eq(true)
  end

  it 'negative gtr' do
    # [version, range, loose]
    # Version should NOT be greater than range
    expect(SemanticRange.gtr('0.6.1-1', '~0.6.1-1', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '1.0.0 - 2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('0.9.9', '1.0.0 - 2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.0', '1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.4', '>=*', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.0', '', true)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '*', false)).to eq(false)
    expect(SemanticRange.gtr('v1.2.3-foo', '*', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.0', '>=1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.1', '>=1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.1.0', '>=1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.1', '>1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.1.0', '>1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('2.0.0', '<=2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.9999.9999', '<=2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.9', '<=2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.9999.9999', '<2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.9', '<2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.0', '>= 1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.1', '>=  1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.1.0', '>=   1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.1', '> 1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.1.0', '>  1.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('2.0.0', '<=   2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.9999.9999', '<= 2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.9', '<=  2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.9999.9999', '<    2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.9', '<\t2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('v0.1.97', '>=0.1.97', false)).to eq(false)
    expect(SemanticRange.gtr('0.1.97', '>=0.1.97', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.4', '0.1.20 || 1.2.4', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.4', '0.1.20 || >1.2.4', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '0.1.20 || 1.2.4', false)).to eq(false)
    expect(SemanticRange.gtr('0.1.20', '0.1.20 || 1.2.4', false)).to eq(false)
    expect(SemanticRange.gtr('0.0.0', '>=0.2.3 || <0.0.1', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.3', '>=0.2.3 || <0.0.1', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.4', '>=0.2.3 || <0.0.1', false)).to eq(false)
    expect(SemanticRange.gtr('1.3.4', '||', false)).to eq(false)
    expect(SemanticRange.gtr('2.1.3', '2.x.x', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '1.2.x', false)).to eq(false)
    expect(SemanticRange.gtr('2.1.3', '1.2.x || 2.x', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '1.2.x || 2.x', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', 'x', false)).to eq(false)
    expect(SemanticRange.gtr('2.1.3', '2.*.*', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '1.2.*', false)).to eq(false)
    expect(SemanticRange.gtr('2.1.3', '1.2.* || 2.*', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '1.2.* || 2.*', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '1.2.* || 2.*', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '*', false)).to eq(false)
    expect(SemanticRange.gtr('2.1.2', '2', false)).to eq(false)
    expect(SemanticRange.gtr('2.3.1', '2.3', false)).to eq(false)
    expect(SemanticRange.gtr('2.4.0', '~2.4', false)).to eq(false)
    expect(SemanticRange.gtr('2.4.5', '~2.4', false)).to eq(false)
    expect(SemanticRange.gtr('3.2.2', '~>3.2.1', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '~1', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '~>1', false)).to eq(false)
    expect(SemanticRange.gtr('1.2.3', '~> 1', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.2', '~1.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.2', '~ 1.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.0', '>=1', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.0', '>= 1', false)).to eq(false)
    expect(SemanticRange.gtr('1.1.1', '<1.2', false)).to eq(false)
    expect(SemanticRange.gtr('1.1.1', '< 1.2', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.0beta', '1', true)).to eq(false)
    expect(SemanticRange.gtr('0.5.5', '~v0.5.4-pre', false)).to eq(false)
    expect(SemanticRange.gtr('0.5.4', '~v0.5.4-pre', false)).to eq(false)
    expect(SemanticRange.gtr('0.7.2', '=0.7.x', false)).to eq(false)
    expect(SemanticRange.gtr('0.7.2', '>=0.7.x', false)).to eq(false)
    expect(SemanticRange.gtr('0.7.0-asdf', '=0.7.x', false)).to eq(false)
    expect(SemanticRange.gtr('0.7.0-asdf', '>=0.7.x', false)).to eq(false)
    expect(SemanticRange.gtr('0.6.2', '<=0.7.x', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.5', '>0.2.3 >0.2.4 <=0.2.5', false)).to eq(false)
    expect(SemanticRange.gtr('0.2.4', '>=0.2.3 <=0.2.4', false)).to eq(false)
    expect(SemanticRange.gtr('2.0.0', '1.0.0 - 2.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('0.0.0-0', '^1', false)).to eq(false)
    expect(SemanticRange.gtr('2.0.0', '^3.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('2.0.0', '^1.0.0 || ~2.0.1', false)).to eq(false)
    expect(SemanticRange.gtr('3.2.0', '^0.1.0 || ~3.0.1 || 5.0.0', false)).to eq(false)
    expect(SemanticRange.gtr('1.0.0beta', '^0.1.0 || ~3.0.1 || 5.0.0', true)).to eq(false)
    expect(SemanticRange.gtr('5.0.0-0', '^0.1.0 || ~3.0.1 || 5.0.0', true)).to eq(false)
    expect(SemanticRange.gtr('3.5.0', '^0.1.0 || ~3.0.1 || >4 <=5.0.0', false)).to eq(false)
  end
end
